repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        exclude: "^(docs/|models/|data/|reports/|references|notebooks/|assets/|scripts/|runs/)"
        args: ["--experimental-string-processing"]

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args: ["--max-line-length", "88", "--ignore=D202", "--ignore=D100"]
        additional_dependencies: [flake8-docstrings]
        exclude: "^(docs/|models/|data/|reports/|references|notebooks/|assets/|scripts/|runs/)"
