# Global
seed: 101
input_height: 128 # For resizing and model creation
input_width: 128 # For resizing and model creation
# n_channels must be set in code based on dataset and task

src_code_path: 'src' # put '' if packages are in root directory of your repository
data_dir: 'assets/EchoNet-Dynamic'

# Classes
data_loader_class: dataset.DataLoader # Required
model_builder_class: model.UNetBaselineBuilder # Required
preprocessor_class: dataset.Preprocessor # Required
augmentor_class: dataset.Augmentor
evaluator_class: evaluation.Evaluator

# Epochs
epochs: 10

# Batch-size
batch_size: 32

# Parameters for instantiating DataLoader
data_loader:
  shuffle: True # on training data
  split_ratio: 0.9
  to_fit: True
  dataset_features:
    age: [ 18, 100 ]
    sex: [ "M", "F" ]
    stage: [ "ES", "ED" ]
    image_quality: [ "Poor", "Medium", "Good" ]
    view: [ "4CH" ]


# Parameters for model-builder
model_builder:
  optimizer:
    type: "adam"
    initial_lr: 0.0001
  loss_type: "binary_crossentropy"
  metrics: ['acc']
  inference_threshold: 0.5

# Parameters for instantiating Preprocessor
preprocessor:
  normalization_type: null
  format: "gray_scale"
  max: 255
  min: 0
  do_resizing: True
  do_normalization: True


# Parameters for instantiating augmentation
do_train_augmentation: True
do_validation_augmentation: False
augmentor:
  rotation_proba: 0.5
  rotation_range: 45
  flip_proba: 0.5

# Parameters for exporting, will be used by trainer
export:
  metric: "val_loss"
  mode: "min"
